---
# tasks file for ansible-role-nginx_controller_application

- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  loop:
    - api_version
    - controller.fqdn
    - controller.auth_token
    - environmentName
    - app.metadata.name

- name: Form the component url
  set_fact:
    app_url: >-
      https://{{ controller.fqdn }}/{{ api_version }}/services/environments/{{ environmentName }}/apps/{{ app.metadata.name }}

- name: Test for application
  uri:
    url: "{{ app_url }}"
    method: "GET"
    status_code:
      - 200
      - 201
      - 404
    return_content: yes
    validate_certs: "{{ controller.validate_certs | default(false) }}"
    headers:
      Cookie: "{{ controller.auth_token }}"
  register: app_status

- name: create if app is absent
  uri:
    url: "{{ app_url }}"
    method: "PUT"
    body: "{{ app }}"
    body_format: json
    status_code:
      - 200
      - 201
      - 202
    return_content: yes
    validate_certs: "{{ controller.validate_certs | default(false) }}"
    headers:
      Cookie: "{{ controller.auth_token }}"
  when: app_status.status == 404
